---
- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Render nginx site
  ansible.builtin.template:
    src: shell-space.conf.j2
    dest: /etc/nginx/sites-available/shell-space.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload nginx

- name: Enable nginx site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/shell-space.conf
    dest: /etc/nginx/sites-enabled/shell-space.conf
    state: link
  notify: Reload nginx

- name: Disable default nginx site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Reload nginx

- name: Enable nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
